/**
 * CyberForge AI - Question Database
 * 20 Questions per Topic
 */

const QuestionPool = {
    // === BEGINNER: CYBERSECURITY ===
    'intro': [
        { q: "What does the 'C' in the CIA Triad stand for?", a: ["Confidentiality", "Circumvention", "Cloud", "Cyber"], correct: 0 },
        { q: "Which of these is a 'Zero-Day' vulnerability?", a: ["One that has been patched", "A hole in software with no available patch", "A vulnerability discovered at midnight", "A very old bug"], correct: 1 },
        { q: "What is the primary goal of an ethical hacker?", a: ["To steal data", "To disrupt services", "To find and help fix security vulnerabilities", "To gain fame"], correct: 2 },
        { q: "What does 'PII' stand for?", a: ["Private Internet Information", "Personally Identifiable Information", "Public Interface Identity", "Personal Internal IP"], correct: 1 },
        { q: "Which type of attacker is typically motivated by social or political causes?", a: ["Script Kiddie", "State-Sponsored Actor", "Hacktivist", "Insider Threat"], correct: 2 },
        { q: "In the CIA triad, 'Integrity' refers to:", a: ["Ensuring data is only seen by authorized users", "Ensuring data is accurate and untampered", "Ensuring systems are always up", "Ensuring clean physical hardware"], correct: 1 },
        { q: "Which of these is a common 'Social Engineering' technique?", a: ["SQL Injection", "Brute Force", "Pretexting", "Rootkit installation"], correct: 2 },
        { q: "What is 'Shoulder Surfing'?", a: ["Surfing the web in public", "Peeking at someone's screen or keyboard", "Riding a surfboard", "Remote desktop monitoring"], correct: 1 },
        { q: "Which of these is a biometric factor?", a: ["PIN", "Fingerprint", "Smart Card", "Password"], correct: 1 },
        { q: "What is an 'Insider Threat'?", a: ["A virus inside a file", "An employee who misuse their access", "A hacker from another country", "A firewall error"], correct: 1 },
        { q: "The process of verifying a user's identity is called:", a: ["Authorization", "Accounting", "Authentication", "Auditing"], correct: 2 },
        { q: "Which of these is 'Metadata'?", a: ["The content of an email", "The size and timestamp of a file", "The encrypted password", "The user's biometrics"], correct: 1 },
        { q: "What does MFA stand for?", a: ["Multi-File Access", "Multi-Factor Authentication", "Main Firewall Application", "Managed Filter Attack"], correct: 1 },
        { q: "A 'White Hat' hacker is another name for:", a: ["A dangerous criminal", "An ethical security specialist", "A beginner hacker", "A corporate spy"], correct: 1 },
        { q: "What is 'Eavesdropping' in a digital context?", a: ["Unauthorized interception of communication", "Loudly talking in a server room", "Cleaning a database", "Publicly posting secrets"], correct: 0 },
        { q: "Which document defines the rules for using a company's technology?", a: ["Terms of Service", "Acceptable Use Policy (AUP)", "Privacy Manual", "Service Level Agreement"], correct: 1 },
        { q: "What is 'Dumping' in physical security?", a: ["Deleting files", "Searching through trash for sensitive info", "Exiting a building", "Clearing RAM"], correct: 1 },
        { q: "Which of these is an example of 'Availability'?", a: ["Changing a password", "Encryption", "Regular backups and redundant servers", "Input validation"], correct: 2 },
        { q: "What is 'Whaling'?", a: ["Attacking a large database", "A phishing attack targeting high-level executives", "Searching for big data", "A type of network loop"], correct: 1 },
        { q: "The 'Principle of Least Privilege' means:", a: ["Everyone gets admin access", "Users only get the access needed for their job", "Users get no access at all", "Security is optional"], correct: 1 }
    ],

    'password': [
        { q: "What is a 'Passphrase'?", a: ["A single complex word", "A long string of random words", "A sequence of numbers", "A type of biometric"], correct: 1 },
        { q: "Why is password reuse dangerous?", a: ["It's too hard to remember", "One breach exposes all accounts", "Passwords expire too fast", "It slows down the login process"], correct: 1 },
        { q: "Which of these makes a password stronger?", a: ["Regular words", "Using your birth year", "Increased length and character variety", "Keeping it under 6 characters"], correct: 2 },
        { q: "What is a 'Brute Force' attack?", a: ["Asking a user for their password", "Trying every possible combination of characters", "Stealing a physical key", "Using a common dictionary list"], correct: 1 },
        { q: "Which tool stores and generates unique passwords securely?", a: ["Excel", "Notepad", "Password Manager", "Browser History"], correct: 2 },
        { q: "What is 'Salting' a password?", a: ["Adding random data to a password before hashing", "Making a password taste better", "Changing it every 30 days", "Using uppercase letters"], correct: 0 },
        { q: "A 'Dictionary Attack' uses:", a: ["A list of common words and known passwords", "A physical dictionary", "Random characters", "Biometric data"], correct: 0 },
        { q: "How often should you ideally change a password after a breach notification?", a: ["Next year", "Never", "Immediately", "When you feel like it"], correct: 2 },
        { q: "What does 'TOTP' stand for?", a: ["Total Output Time Phase", "Time-based One-Time Password", "Trusted Online Transfer Protocol", "Two-Option Task Protocol"], correct: 1 },
        { q: "Which is more secure than SMS-based MFA?", a: ["No MFA", "Hardware Keys (YubiKey)", "Personal security questions", "Writing it on a sticky note"], correct: 1 },
        { q: "Credential stuffing is an attack where:", a: ["Hackers guess passwords manually", "Automated tools use breached credentials from one site on others", "A user types too fast", "Servers are overloaded"], correct: 1 },
        { q: "Which of these is a common hashing algorithm for passwords?", a: ["AES", "bcrypt", "RSA", "Diffie-Hellman"], correct: 1 },
        { q: "True or False: Hashing is a one-way process.", a: ["True", "False"], correct: 0 },
        { q: "What is the 'Keychain' on macOS/iOS?", a: ["A physical key set", "A built-in password management system", "A social network", "A type of malware"], correct: 1 },
        { q: "Which character length is generally considered a baseline for a strong passphrase?", a: ["6", "8", "At least 12-16", "Exactly 4"], correct: 2 },
        { q: "What is 'Sticky Note Security'?", a: ["A type of firewall", "Writing passwords on physical notes near the device", "Using digital sticky notes", "An encrypted memo"], correct: 1 },
        { q: "Which of these is NOT a good password practice?", a: ["Using a manager", "Sharing it with your IT friend", "Enabling MFA", "Unique passwords for all sites"], correct: 1 },
        { q: "What is a 'Passkey'?", a: ["A new biometric-linked cryptographic login", "Another word for password", "A physical door key", "A type of recovery code"], correct: 0 },
        { q: "In MFA, which factor is 'Something you know'?", a: ["Fingerprint", "Smartphone", "Password", "Location"], correct: 2 },
        { q: "What is 'Rainbow Table'?", a: ["A decorative table", "A precomputed table for reversing password hashes", "A list of colorful passwords", "A type of encrypted wifi"], correct: 1 }
    ],

    'phishing': [
        { q: "What is 'Smishing'?", a: ["Phishing via email", "Phishing via SMS/text", "Phishing via phone call", "Phishing via social media"], correct: 1 },
        { q: "A phishing attack targeting a specific individual or organization is called:", a: ["Bulk Phishing", "Spear Phishing", "Whaling", "Vishing"], correct: 1 },
        { q: "What is 'Vishing'?", a: ["Visual Phishing", "Voice Phishing (phone calls)", "Very fast phishing", "Virtual Phishing"], correct: 1 },
        { q: "Which of these is a red flag in a phishing email?", a: ["Correct spelling", "Urgent/threatening language", "The sender's real name", "Links to official sites"], correct: 1 },
        { q: "What should you do if you receive a suspicious email from your bank?", a: ["Click the link to verify", "Reply and ask if it's real", "Call the bank using a known official number", "Delete it immediately without checking"], correct: 2 },
        { q: "What is 'Pharming'?", a: ["Growing a virus", "Redirecting a user to a fake website by poisoning DNS", "A type of email spam", "Stealing hardware"], correct: 1 },
        { q: "Which technique involves creating a fake login page that looks identical to a real one?", a: ["Credential Harvesting", "Packet Sniffing", "Man-in-the-Middle", "SQLi"], correct: 0 },
        { q: "What does 'hovering' over a link help you see?", a: ["The link's destination URL", "The sender's IP", "The email's font size", "The recipient's list"], correct: 0 },
        { q: "A 'Sense of Urgency' in an email is used to:", a: ["Be helpful", "Make the user act without thinking", "Show the importance of the task", "Test the user's speed"], correct: 1 },
        { q: "What is 'Angler Phishing'?", a: ["Phishing for fisherman", "Using fake social media customer service accounts", "A type of phishing in the ocean", "Fishing for emails"], correct: 1 },
        { q: "In 'Business Email Compromise' (BEC), attackers often:", a: ["Mimic a high-level executive to authorize payments", "Send random spam", "Hack the company website", "Delete the email server"], correct: 0 },
        { q: "What is a 'Typosquatted' domain?", a: ["A professional domain", "A URL that looks like a real one but with a typo (e.g., g00gle.com)", "A domain for typists", "A high-speed domain"], correct: 1 },
        { q: "True or False: Most successful breaches start with a phishing email.", a: ["True", "False"], correct: 0 },
        { q: "What is the purpose of a 'Phishing Simulation'?", a: ["To hack employees", "To train employees to recognize and report phishing", "To play a game", "To slow down the network"], correct: 1 },
        { q: "Which tech helps prevent your domain from being used in phishing?", a: ["HTTPS", "DMARC/SPF/DKIM", "HTML5", "TCP/IP"], correct: 1 },
        { q: "What is 'QRishing'?", a: ["Cleaning a monitor", "Phishing via malicious QR codes", "A fast type of phishing", "Phishing for crypto"], correct: 1 },
        { q: "If an email says 'You have won $1M, click here', it is likely:", a: ["A generous gift", "A phishing scam", "A browser notification", "A system update"], correct: 1 },
        { q: "What is 'Consent Phishing'?", a: ["Asking for a password", "Tricking users into granting permissions to a malicious app", "A type of survey", "A friendly email"], correct: 1 },
        { q: "Why do attackers use 'Link Shorteners' in phishing?", a: ["To be neat", "To hide the suspicious destination URL", "To save space", "To speed up the internet"], correct: 1 },
        { q: "What is the first thing you should do when you spot a phishing email at work?", a: ["Delete it", "Forward it to everyone", "Report it to your security/IT team", "Try to hack the sender"], correct: 2 }
    ],

    'malware': [
        { q: "What is 'Ransomware'?", a: ["Ad-supported software", "Malware that encrypts files and demands payment", "A type of firewall", "A free system cleaner"], correct: 1 },
        { q: "Which type of malware can replicate itself across a network without human interaction?", a: ["Virus", "Worm", "Trojan", "Spyware"], correct: 1 },
        { q: "A 'Trojan Horse' is malware that:", a: ["Lives in a wooden horse", "Disguises itself as legitimate software", "Spreads like a fever", "Protects the computer"], correct: 1 },
        { q: "What is 'Spyware'?", a: ["Software that spies on users without consent", "A tool for private investigators", "A type of search engine", "A game about spies"], correct: 0 },
        { q: "What is a 'Keylogger'?", a: ["A tool to unlock keys", "Malware that records every keystroke", "A sequence of notes", "A type of keyboard driver"], correct: 1 },
        { q: "What is a 'Botnet'?", a: ["A network of robots", "A network of compromised computers controlled by an attacker", "A type of internet speed", "A security team"], correct: 1 },
        { q: "What is 'Adware'?", a: ["Software for advertising agencies", "Malware that displays unwanted advertisements", "A type of video player", "A system optimizer"], correct: 1 },
        { q: "What is a 'Rootkit'?", a: ["A tool for gardening", "Malware that gains administrative control while hiding its presence", "A type of operating system", "A boot sequence"], correct: 1 },
        { q: "Which type of malware is designed to look like a popup saying your computer is infected?", a: ["Adware", "Scareware", "Spyware", "Ransomware"], correct: 1 },
        { q: "What is 'Logic Bomb'?", a: ["A very smart bomb", "Malware that triggers a malicious action when a condition is met", "A type of logic game", "A coding error"], correct: 1 },
        { q: "What is 'Fileless' malware?", a: ["Malware that uses no files", "Malware that operates entirely in memory", "A type of cloud storage", "A broken program"], correct: 1 },
        { q: "What is 'Polymorphic' malware?", a: ["Malware with many shapes", "Malware that changes its code to evade signature detection", "A type of science project", "A slow virus"], correct: 1 },
        { q: "What is 'C&C' or 'C2' server?", a: ["A coffee and cream server", "A command-and-control server used to manage botnets", "A cloud computing server", "A local network hub"], correct: 1 },
        { q: "What does 'Zero-Day' mean in malware context?", a: ["A very clean computer", "A new threat with no known defense or signature", "A fast malware", "A malware that expires in a day"], correct: 1 },
        { q: "What is a 'Backdoor'?", a: ["A rear exit in a data center", "A hidden entry point into a system that bypasses security", "A type of firewall", "A login screen"], correct: 1 },
        { q: "What is 'Crypto-jacking'?", a: ["Stealing a car", "Unauthorized use of a computer to mine cryptocurrency", "Hacking a bank", "A type of encryption"], correct: 1 },
        { q: "What is 'Stuxnet' famous for?", a: ["Being the first virus", "Targeting industrial control systems (SCADA)", "Spreading via email", "Being a joke"], correct: 1 },
        { q: "How does a 'Virus' typically spread?", a: ["By physical contact", "By attaching itself to a host file or program", "By itself across wifi", "By magically appearing"], correct: 1 },
        { q: "What is a 'Sandbox' in malware analysis?", a: ["A place for kids", "An isolated environment for safely running suspicious programs", "A type of hard drive", "A secure operating system"], correct: 1 },
        { q: "What is the primary way to protect against known malware?", a: ["Running common sense", "Regularly updated Antivirus/Antimalware software", "Unplugging the internet", "Using a complex password"], correct: 1 }
    ],

    'networking': [
        { q: "What does IP stand for?", a: ["Interest Protocol", "Internet Protocol", "Internal Process", "Identity Point"], correct: 1 },
        { q: "Which protocol is used for secure web browsing?", a: ["HTTP", "HTTPS", "FTP", "SMTP"], correct: 1 },
        { q: "What is the purpose of a Firewall?", a: ["To keep a room warm", "To filter network traffic and block unauthorized access", "To speed up the internet", "To store data"], correct: 1 },
        { q: "What does DNS do?", a: ["Deletes Network Settings", "Translates domain names (like google.com) to IP addresses", "Distributes Network Storage", "Defines Network Standards"], correct: 1 },
        { q: "Which device connects multiple devices on a local network (LAN) and manages traffic?", a: ["Router", "Switch", "Modem", "Server"], correct: 1 },
        { q: "What is a 'Man-in-the-Middle' (MITM) attack?", a: ["A physical intruder", "An attacker intercepting communication between two parties", "A server error", "A type of load balancer"], correct: 1 },
        { q: "What does MAC address identify?", a: ["A computer made by Apple", "The unique physical address of a network interface", "The user's account", "The internet service provider"], correct: 1 },
        { q: "Which protocol is used to assign IP addresses automatically?", a: ["DNS", "DHCP", "FTP", "SSH"], correct: 1 },
        { q: "What is a 'VPN'?", a: ["Very Private Network", "Virtual Private Network", "Visual Process Node", "Verified Path Name"], correct: 1 },
        { q: "Which port is commonly used for HTTPS?", a: ["80", "443", "22", "21"], correct: 1 },
        { q: "What is 'Packet Sniffing'?", a: ["Checking for drugs", "Capturing network traffic for analysis", "A slow network", "A type of router signal"], correct: 1 },
        { q: "What does 'LAN' stand for?", a: ["Legal Area Node", "Local Area Network", "Log Access Name", "Large Area Network"], correct: 1 },
        { q: "What is a 'Denial of Service' (DoS) attack?", a: ["Helping a user", "Attempting to crash a service by overwhelming it with traffic", "A type of password guess", "A file deletion"], correct: 1 },
        { q: "Which layer of the OSI model handles routing?", a: ["Data Link", "Network", "Transport", "Physical"], correct: 1 },
        { q: "What is 'SSID'?", a: ["Secure System ID", "Service Set Identifier (the name of a Wi-Fi network)", "Signal Strength Index", "Software System ID"], correct: 1 },
        { q: "What does 'Port Scanning' do?", a: ["Cleans a port", "Checks for open ports on a system to find vulnerabilities", "Speeds up downloads", "Deletes data"], correct: 1 },
        { q: "Which protocol is used for remote command-line access securely?", a: ["Telnet", "SSH", "HTTP", "FTP"], correct: 1 },
        { q: "What is a 'Default Gateway'?", a: ["A physical door", "The node that serves as an access point to another network", "The main computer", "A type of authentication"], correct: 1 },
        { q: "What is 'ICMP' commonly used for?", a: ["File Transfer", "Diagnostic tools like PING", "Email", "Web browsing"], correct: 1 },
        { q: "What does 'Subnet Mask' define?", a: ["The user's mask", "Which part of an IP address is the network and which is the host", "The server's name", "The internet speed"], correct: 1 }
    ],

    'web': [
        { q: "What does HTML stand for?", a: ["Hyper Tool Markup Language", "Hypertext Markup Language", "High Tech Main Link", "Hyperlink Text Mode Logic"], correct: 1 },
        { q: "Which protocol is the unencrypted version of HTTPS?", a: ["SSH", "FTP", "HTTP", "SMTP"], correct: 2 },
        { q: "What is a 'Cookie' in web browsing?", a: ["A type of snack", "A small piece of data stored on the user's computer by the web browser", "A virus", "A large database"], correct: 1 },
        { q: "What does a '404 Not Found' error mean?", a: ["The server is down", "The requested page does not exist on the server", "Your internet is slow", "The page is private"], correct: 1 },
        { q: "What is 'SQL Injection'?", a: ["A way to speed up databases", "Injecting malicious SQL code to manipulate a database", "A type of web design", "A network attack"], correct: 1 },
        { q: "What does 'XSS' stand for?", a: ["Extreme Security System", "Cross-Site Scripting", "XML Script Selection", "Extended Simple Service"], correct: 1 },
        { q: "What is a 'Session'?", a: ["A meeting", "The period of time a user stays logged into a website", "A type of cookie", "A server reboot"], correct: 1 },
        { q: "Which part of a URL is the top-level domain (TLD) in 'google.com'?", a: ["google", ".com", "https://", "www"], correct: 1 },
        { q: "What is 'CSRF'?", a: ["Cross-Site Request Forgery", "Cyber Security Response File", "Common System Rescue Form", "Cloud Storage Recovery Feature"], correct: 0 },
        { q: "What does 'OWASP' stand for?", a: ["Online Web Application Security Project", "Open Worldwide Application Security Project", "Official Web Audit Security Protocol", "Open Web Account Safety Program"], correct: 1 },
        { q: "What is a 'WAF'?", a: ["Web Application Firewall", "Wireless Access Form", "Website Account Filter", "Web Analytics File"], correct: 0 },
        { q: "Which HTTP method is typically used to retrieve data?", a: ["POST", "GET", "PUT", "DELETE"], correct: 1 },
        { q: "Which HTTP method is typically used to send new data to a server?", a: ["GET", "POST", "HEAD", "OPTIONS"], correct: 1 },
        { q: "What is the 'DOM' in web development?", a: ["Data Object Mode", "Document Object Model", "Digital Office Mail", "Domain Object Main"], correct: 1 },
        { q: "What is 'Rate Limiting'?", a: ["Limiting internet speed", "Limiting the number of requests a user can make in a certain time", "A type of pricing", "A server capacity"], correct: 1 },
        { q: "What is 'Clickjacking'?", a: ["Stealing a mouse", "Tricking a user into clicking something different than what they perceive", "Fast clicking", "A type of game"], correct: 1 },
        { q: "What is 'Input Sanitization'?", a: ["Cleaning a keyboard", "Cleaning user input to prevent attacks like SQLi or XSS", "Deleting logs", "Formatting a drive"], correct: 1 },
        { q: "What does 'TLS' stand for?", a: ["Total Link Security", "Transport Layer Security", "Tactical Line System", "Transfer Level Standard"], correct: 1 },
        { q: "What is 'Directory Traversal'?", a: ["Moving through a folder", "An attack to access files outside the intended web root directory", "A type of search", "A map of a site"], correct: 1 },
        { q: "What is an 'IDOR' vulnerability?", a: ["Insecure Direct Object Reference", "Internal Data Object Recovery", "Identity Digital Online Record", "Insecure Digital Office Route"], correct: 0 }
    ],

    'vulnerabilities': [
        { q: "What is a 'Buffer Overflow'?", a: ["A leaky bucket", "Writing more data to a buffer than it can hold, leading to a crash or exploit", "A fast internet", "A memory upgrade"], correct: 1 },
        { q: "Which vulnerability occurs when a program allows a user to specify a path to a file?", a: ["SQLi", "Local File Inclusion (LFI)", "XSS", "Brute Force"], correct: 1 },
        { q: "What is a 'Race Condition'?", a: ["A fast hacker", "A flaw where the outcome depends on the timing of events", "A network competition", "A server race"], correct: 1 },
        { q: "What is 'Dangling Pointer'?", a: ["A pointer that doesn't work", "A pointer that points to a memory location that has been deleted", "A type of mouse cursor", "A coding style"], correct: 1 },
        { q: "What is 'Deserialization' vulnerability?", a: ["A breakfast error", "Insecurely converting data back into an object, potentially executing code", "A slow network", "A file deletion"], correct: 1 },
        { q: "Which vulnerability involves a server taking a user-supplied URL and making a request to it?", a: ["CSRF", "Server-Side Request Forgery (SSRF)", "XSS", "SQLi"], correct: 1 },
        { q: "What is 'Broken Access Control'?", a: ["A broken door", "Unauthorized users being able to access restricted data or functions", "A slow login", "A server crash"], correct: 1 },
        { q: "Which vulnerability is caused by missing encryption on sensitive data?", a: ["XSS", "Cryptographic Failure", "Injection", "Broken Authentication"], correct: 1 },
        { q: "What is 'Security Misconfiguration'?", a: ["A bad setup", "Using default settings, open cloud storage, or verbose error messages", "A type of firewall", "A slow PC"], correct: 1 },
        { q: "What is 'Vulnerable and Outdated Components'?", a: ["Old hardware", "Using software with known, unpatched vulnerabilities", "A slow internet", "A type of virus"], correct: 1 },
        { q: "What is 'Insecure Design'?", a: ["An ugly website", "A broad category of flaws related to architecture and design failures", "A broken link", "A slow database"], correct: 1 },
        { q: "What is 'Software and Data Integrity Failures'?", a: ["A broken file", "Unauthorized changes to software or data (e.g., unsigned updates)", "A slow server", "A type of bug"], correct: 1 },
        { q: "What is 'Security Logging and Monitoring Failures'?", a: ["No logs", "Failing to detect an attack because of missing or poor logs", "A slow screen", "A type of error"], correct: 1 },
        { q: "What is a 'Zero-Day' exploit?", a: ["An exploit released on day zero", "An exploit for a vulnerability that is unknown to the vendor", "A fast exploit", "A type of patch"], correct: 1 },
        { q: "What is 'Memory Leak'?", a: ["Spilling water on RAM", "Software failing to release memory it no longer needs", "A type of storage", "A fast computer"], correct: 1 },
        { q: "What is 'Command Injection'?", a: ["Typing fast", "Executing arbitrary commands on the host operating system via a vulnerable app", "A type of search", "A network error"], correct: 1 },
        { q: "What is 'Integer Overflow'?", a: ["Too many numbers", "A condition where a numerical value exceeds the maximum size allowed", "A slow calculation", "A type of database"], correct: 1 },
        { q: "What is 'Open Redirect'?", a: ["A door that stays open", "Redirecting a user to an external, potentially malicious site", "A type of link", "A server update"], correct: 1 },
        { q: "What is 'XML External Entity (XXE)'?", a: ["A scary ghost", "A type of attack against an application that parses XML input", "A type of file", "A network protocol"], correct: 1 },
        { q: "What is a 'CVE'?", a: ["Common Vulnerabilities and Exposures", "Cyber Vulnerability Engine", "Common Virus Entry", "Central Vulnerability Error"], correct: 0 }
    ],

    'ossecurity': [
        { q: "What is 'Root' or 'Administrator' account?", a: ["A basic user", "The account with full control over the operating system", "A guest account", "A service account"], correct: 1 },
        { q: "Which principle restricts users to only the access they need?", a: ["Everything for Everyone", "Principle of Least Privilege", "Open Access Policy", "Standard User Mode"], correct: 1 },
        { q: "What is a 'Patch'?", a: ["A type of cloth", "A software update designed to fix bugs or security holes", "A type of virus", "A network cable"], correct: 1 },
        { q: "What is 'User Account Control' (UAC) in Windows?", a: ["A login screen", "A feature that asks for permission before making changes", "A type of file manager", "A security alert"], correct: 1 },
        { q: "What is 'Sudo' in Linux?", a: ["A type of soup", "A command that allows users to run programs with security privileges of another user", "A file deletion", "A network tool"], correct: 1 },
        { q: "What is 'Full Disk Encryption'?", a: ["Wiping a drive", "Encrypting every bit of data on a hard drive", "A type of storage", "A fast computer"], correct: 1 },
        { q: "What is a 'Service Account'?", a: ["A customer service account", "An account used by a service or application to run", "A personal account", "A type of bank account"], correct: 1 },
        { q: "What is 'Event Viewer' used for in Windows?", a: ["Watching movies", "Viewing system logs and events", "Browsing the web", "Editing photos"], correct: 1 },
        { q: "What is 'Hardening' of an OS?", a: ["Making it physically strong", "Configuring it to be as secure as possible by removing unused features", "A type of update", "A slow computer"], correct: 1 },
        { q: "What is 'BitLocker'?", a: ["A data thief", "A full disk encryption feature included with Windows", "A type of file", "A network speed"], correct: 1 },
        { q: "What is 'AppArmor' or 'SELinux'?", a: ["A type of antivirus", "Security modules for the Linux kernel that restrict programs", "A screen locker", "A file manager"], correct: 1 },
        { q: "What is 'DEP' (Data Execution Prevention)?", a: ["Deleting files", "A security feature that prevents code from running in non-executable memory", "A fast processor", "A type of update"], correct: 1 },
        { q: "What is 'ASLR' (Address Space Layout Randomization)?", a: ["Moving a house", "Randomly arranging the address space positions of key data areas", "A type of storage", "A network tool"], correct: 1 },
        { q: "Which tool is commonly used to manage users and groups in an enterprise Windows environment?", a: ["Notepad", "Active Directory", "Paint", "Chrome"], correct: 1 },
        { q: "What is a 'Kernel'?", a: ["A seed", "The core part of the operating system that manages hardware", "A type of shell", "A user interface"], correct: 1 },
        { q: "What is 'SSH'?", a: ["Super Secret Hub", "Secure Shell", "System Site Header", "Simple Service Host"], correct: 1 },
        { q: "What is 'File Permissions'?", a: ["Asking to use a file", "Settings that determine who can read, write, or execute a file", "A type of virus", "A storage limit"], correct: 1 },
        { q: "What is 'End of Life' (EOL) software?", a: ["A computer that died", "Software that is no longer supported or patched by the vendor", "A new update", "A fast app"], correct: 1 },
        { q: "What is 'Sandboxing'?", a: ["Playing in sand", "Running an application in an isolated environment", "A type of firewall", "A network speed"], correct: 1 },
        { q: "What is 'Vulnerability Scanning'?", a: ["Looking for bugs", "Using automated tools to find security weaknesses", "A type of antivirus", "A file search"], correct: 1 }
    ],

    // === PROFESSIONAL: CYBERSECURITY ===
    'pentesting': [
        { q: "What is 'Penetration Testing'?", a: ["A type of building inspection", "A simulated cyberattack to find vulnerabilities", "A way to install hardware", "A speed test"], correct: 1 },
        { q: "What is a 'Red Team'?", a: ["A team of firemen", "The offensive security team simulating an attacker", "The defensive security team", "A team of managers"], correct: 1 },
        { q: "What is a 'Blue Team'?", a: ["A sea crew", "The defensive security team that protects systems", "The offensive team", "A research team"], correct: 1 },
        { q: "What is 'Reconnaissance' in pentesting?", a: ["Cleaning a server", "The phase of gathering information about a target", "Exploiting a bug", "Deleting logs"], correct: 1 },
        { q: "What is 'Nmap' used for?", a: ["Drawing world maps", "Network exploration and security auditing (port scanning)", "Writing code", "Editing videos"], correct: 1 },
        { q: "What is 'Metasploit'?", a: ["A type of cryptocurrency", "A powerful exploitation framework used by researchers", "A social media site", "A browser"], correct: 1 },
        { q: "What is 'Burp Suite' primarily used for?", a: ["Cooking", "Web application security testing", "Network routing", "Hardware repair"], correct: 1 },
        { q: "What is 'Privilege Escalation'?", a: ["Getting a promotion", "Gaining higher-level access than intended (e.g., from user to root)", "A network error", "A type of firewall"], correct: 1 },
        { q: "What is a 'Reverse Shell'?", a: ["A decorative shell", "A shell session where the target connects back to the attacker", "A type of encryption", "A broken terminal"], correct: 1 },
        { q: "What is 'Post-Exploitation'?", a: ["Repairing a system", "The phase of a pentest after a target has been compromised", "The initial scanning", "A legal battle"], correct: 1 },
        { q: "What is 'Vulnerability Research'?", a: ["Searching for new bugs in software", "A type of school project", "A data entry job", "A network scan"], correct: 0 },
        { q: "What does 'Lateral Movement' mean?", a: ["Moving a mouse sideways", "Moving from one system to another within a compromised network", "A type of data backup", "A server reboot"], correct: 1 },
        { q: "What is 'OSINT'?", a: ["Open Source Intelligence", "Official System Internal Network", "Online Security International Task", "Operation System Integration Tool"], correct: 0 },
        { q: "Which tool is commonly used for Wi-Fi security testing?", a: ["Aircrack-ng", "Notepad", "Chrome", "Excel"], correct: 0 },
        { q: "What is 'Banner Grabbing'?", a: ["Stealing a flag", "Collecting information from a service's welcome message", "A type of ad", "A network crash"], correct: 1 },
        { q: "What is 'SQLmap'?", a: ["A map of SQL servers", "An automated tool for detecting and exploiting SQL injection flaws", "A type of database", "A coding guide"], correct: 1 },
        { q: "What is a 'Bind Shell'?", a: ["A shell with a book", "A shell session where the attacker connects to a listener on the target", "A type of lock", "A network error"], correct: 1 },
        { q: "What is 'Steganography'?", a: ["A type of geography", "Hiding information within other non-secret data (like an image)", "A type of code", "A network protocol"], correct: 1 },
        { q: "What is a 'Honey Pot'?", a: ["A jar of honey", "A decoy system set up to lure and study attackers", "A sweet deal", "A network speed"], correct: 1 },
        { q: "What is 'Pivot' in pentesting?", a: ["A basketball move", "Using a compromised system to attack others on a separate network", "A type of rotation", "A server change"], correct: 1 }
    ],

    'privilege': [
        { q: "What is 'Privilege Escalation'?", a: ["Losing your account", "Moving from a low-privilege account to a higher-privilege one (e.g., Administrator)", "Asking for more work", "A system update"], correct: 1 },
        { q: "Which of these is a 'Horizontal' privilege escalation?", a: ["User to Root", "User to another User with similar privileges", "User to Admin", "Guest to Mod"], correct: 1 },
        { q: "Which of these is a 'Vertical' privilege escalation?", a: ["User to another User", "Standard User to Root/System", "Guest to Guest", "Admin to Admin"], correct: 1 },
        { q: "What is a 'SUID' bit in Linux?", a: ["A type of error", "A permission bit that allows a user to run a file with the owner's privileges", "A file deletion", "A network tool"], correct: 1 },
        { q: "What is 'DLL Hijacking'?", a: ["Stealing a DLL file", "Exploiting the way Windows searches for and loads DLLs", "A type of virus", "A network speed"], correct: 1 },
        { q: "What is a 'Kernel Exploit'?", a: ["A type of seed", "An attack targeting the core of the OS to gain full control", "A file manager", "A user interface"], correct: 1 },
        { q: "What is 'Token Manipulation'?", a: ["A magic trick", "A technique to masquerade as another user by stealing their security token", "A type of crypto", "A network tool"], correct: 1 },
        { q: "What is 'Escalation via Misconfiguration'?", a: ["A bad setup", "Exploiting weak permissions or insecure settings to gain access", "A type of update", "A slow computer"], correct: 1 },
        { q: "What is 'Exploiting Service Paths' in Windows?", a: ["Walking on a path", "Taking advantage of unquoted service paths with spaces", "A type of file", "A network speed"], correct: 1 },
        { q: "What is 'Escalation via Vulnerable Drivers'?", a: ["A car accident", "Using a driver with security flaws to gain kernel access", "A type of file", "A network tool"], correct: 1 },
        { q: "What is 'Process Injection'?", a: ["A medical procedure", "Executing code within the address space of another running process", "A type of update", "A slow computer"], correct: 1 },
        { q: "What is 'Mimikatz' famous for?", a: ["Being a cat game", "Extracting passwords, hashes, and PINs from memory", "A type of browser", "A network tool"], correct: 1 },
        { q: "What is 'Shadow File' in Linux?", a: ["A scary file", "The file that stores hashed user passwords", "A hidden file", "A type of backup"], correct: 1 },
        { q: "What is 'PowerUp.ps1'?", a: ["A game power-up", "A PowerShell script used for finding common privilege escalation paths in Windows", "A file manager", "A network tool"], correct: 1 },
        { q: "What is 'Escalation via Cron Jobs' in Linux?", a: ["A job search", "Exploiting scheduled tasks running with high privileges", "A type of update", "A slow computer"], correct: 1 },
        { q: "What is 'Whoami' command used for?", a: ["Asking a question", "Displaying the current user's identity", "A type of search", "A network tool"], correct: 1 },
        { q: "What is 'Environment Variable' exploitation?", a: ["A type of weather", "Manipulating variables like PATH to trick a program into running malicious code", "A type of update", "A slow computer"], correct: 1 },
        { q: "What is 'UAC Bypass'?", a: ["A road detour", "Techniques to run programs with elevated privileges without a prompt", "A type of file", "A network tool"], correct: 1 },
        { q: "What is 'Dirty COW'?", a: ["A farm animal", "A famous Linux kernel exploit (CVE-2016-5195)", "A type of milk", "A network speed"], correct: 1 },
        { q: "What is the primary way to prevent privilege escalation?", a: ["Open Access", "Proper patch management and the Principle of Least Privilege", "No security", "Free wifi"], correct: 1 }
    ],

    // === BEGINNER: AI SECURITY ===
    'ai_intro': [
        { q: "What is 'Artificial Intelligence' (AI)?", a: ["A type of robot", "Systems designed to simulate human intelligence", "A very fast calculator", "A search engine"], correct: 1 },
        { q: "What is 'Machine Learning' (ML)?", a: ["A subset of AI that learns from data without explicit programming", "A school for computers", "A type of memory", "A network cable"], correct: 0 },
        { q: "How is AI used in Cybersecurity?", a: ["To play games", "To detect threats and automate responses at scale", "To write emails", "To browse the web"], correct: 1 },
        { q: "What is a 'Neural Network'?", a: ["A network of nerves", "A computing system inspired by the human brain", "A type of wifi", "A server hub"], correct: 1 },
        { q: "What is 'Training Data'?", a: ["Data for exercise", "The data used to teach an AI model how to make predictions", "A type of file", "A network speed"], correct: 1 },
        { q: "What is a 'Model' in AI?", a: ["A fashion star", "The mathematical representation of a process learned from data", "A type of hardware", "A user interface"], correct: 1 },
        { q: "What is 'Deep Learning'?", a: ["Learning while sleeping", "A subset of ML using multiple layers of neural networks", "A type of focus", "A network tool"], correct: 1 },
        { q: "What is 'NLP'?", a: ["Next Line Program", "Natural Language Processing (reading/understanding human speech)", "Network Level Protocol", "Neural Link Protocol"], correct: 1 },
        { q: "What is 'Computer Vision'?", a: ["A monitor", "AI's ability to extract information from digital images and videos", "A type of glasses", "A camera driver"], correct: 1 },
        { q: "What is 'Supervised Learning'?", a: ["Learning with a teacher", "Training a model on labeled data (where answers are known)", "A type of school", "A network speed"], correct: 1 },
        { q: "What is 'Unsupervised Learning'?", a: ["Learning alone", "Training a model on unlabeled data to find hidden patterns", "A type of homework", "A network protocol"], correct: 1 },
        { q: "What is 'Inference'?", a: ["Making a guess", "Using a trained AI model to make predictions on new data", "A type of math", "A server reboot"], correct: 1 },
        { q: "What is a 'False Positive' in AI detection?", a: ["A good thing", "When AI mistakenly identifies harmless activity as a threat", "A type of virus", "A network error"], correct: 1 },
        { q: "What is a 'False Negative' in AI detection?", a: ["A bad thing", "When AI fails to detect an actual threat", "A type of bug", "A server update"], correct: 1 },
        { q: "What is 'Bias' in AI?", a: ["A type of focus", "Systematic errors in an AI model caused by skewed training data", "A type of data", "A network speed"], correct: 1 },
        { q: "What is 'Generative AI'?", a: ["AI that generates power", "AI capable of creating new content like text, images, or music", "A type of battery", "A network hub"], correct: 1 },
        { q: "What is an 'LLM'?", a: ["Large Logic Model", "Large Language Model", "Local Light Mode", "Long Loop Machine"], correct: 1 },
        { q: "What is 'Adversarial Machine Learning'?", a: ["Learning while fighting", "The study of attacks on AI/ML models", "A type of training", "A network defense"], correct: 1 },
        { q: "What is 'Explainable AI' (XAI)?", a: ["A talking robot", "AI designed so that its decisions can be understood by humans", "A type of manual", "A network log"], correct: 1 },
        { q: "Why is 'Data Privacy' critical in AI?", a: ["To save space", "Because AI models are often trained on sensitive personal data", "A type of speed", "A network law"], correct: 1 }
    ],

    'ai_detection': [
        { q: "In AI security, what is a 'Feature'?", a: ["A product benefit", "A specific measurable property used by a model (e.g., packet size)", "A type of app", "A network speed"], correct: 1 },
        { q: "What is 'Malware Signature' vs AI detection?", a: ["A type of name", "Signatures match known files; AI predicts behavior based on patterns", "A type of pen", "A network protocol"], correct: 1 },
        { q: "How can AI help with Phishing detection?", a: ["By sending emails", "By analyzing language patterns and sender reputation in real-time", "By deleting files", "By browsing the web"], correct: 1 },
        { q: "What is 'UEBA'?", a: ["User and Entity Behavior Analytics", "Universal Email Binary Analysis", "User Encryption Base Alpha", "Underground Extreme Byte Action"], correct: 0 },
        { q: "What is an 'Anomaly' in network traffic?", a: ["A normal packet", "Traffic that deviates significantly from the established baseline", "A type of speed", "A server reboot"], correct: 1 },
        { q: "What is 'Clustering' in AI security?", a: ["Grouping things together", "Grouping similar events to find outliers or patterns in attacks", "A type of drive", "A network hub"], correct: 1 },
        { q: "What is 'Log Analysis' with AI?", a: ["Reading a book", "Using AI to sift through millions of log entries to find threats", "A type of math", "A network speed"], correct: 1 },
        { q: "What is 'Sandboxing' + AI?", a: ["Playing in sand", "Running malware in a sandbox and using AI to analyze its impact", "A type of toy", "A server update"], correct: 1 },
        { q: "What is 'Threat Intelligence' integration?", a: ["Reading news", "Feeding global attack data into an AI model for better prediction", "A type of spy", "A network speed"], correct: 1 },
        { q: "What is 'SIEM' enhancement with AI?", a: ["A fast car", "Using AI to reduce alert fatigue and prioritize critical security events", "A type of screen", "A server hub"], correct: 1 },
        { q: "What is 'Zero-Trust' + AI?", a: ["Trusting no one", "Using AI to continuously verify user identity and device health", "A type of lock", "A network speed"], correct: 1 },
        { q: "What is 'Real-time' detection?", a: ["Detection tomorrow", "Detecting a threat as it happens, not hours later", "A type of clock", "A server update"], correct: 1 },
        { q: "What is 'Evasion' in AI detection?", a: ["Hiding in a box", "When an attacker slightly modifies malware to avoid AI detection", "A type of speed", "A network protocol"], correct: 1 },
        { q: "What is 'Heuristic' analysis?", a: ["A type of plant", "Experience-based techniques for problem solving; used in AI for pattern matching", "A type of search", "A server reboot"], correct: 1 },
        { q: "What is 'Sentiment Analysis' in phishing?", a: ["Checking feelings", "Analyzing the tone and urgency of text to identify scams", "A type of emoji", "A network speed"], correct: 1 },
        { q: "What is 'Endpoint Detection and Response' (EDR) AI?", a: ["A type of mouse", "AI running on local devices to detect and block malicious activity", "A type of screen", "A server hub"], correct: 1 },
        { q: "What is 'Vulnerability Managed' AI?", a: ["Fixing bugs", "Using AI to predict which vulnerabilities are most likely to be exploited", "A type of patch", "A network tool"], correct: 1 },
        { q: "What is 'Automated Triage'?", a: ["A fast ambulance", "AI automatically sorting and responding to low-level security alerts", "A type of doctor", "A server update"], correct: 1 },
        { q: "What is 'Fingerprinting' in AI?", a: ["Taking a photo", "Creating unique profiles for users or devices to detect impersonation", "A type of ink", "A network speed"], correct: 1 },
        { q: "What is the biggest challenge for AI detection?", a: ["Not enough electricity", "Adversarial attacks designed to fool the model", "A slow screen", "A network law"], correct: 1 }
    ],

    'ai_dataset': [
        { q: "What is a 'Dataset'?", a: ["A set of data", "A collection of data used for training and testing AI models", "A type of drive", "A network speed"], correct: 1 },
        { q: "What is 'Poisoning' a dataset?", a: ["Adding poison", "Injecting malicious data into the training set to corrupt the AI model", "A type of virus", "A server reboot"], correct: 1 },
        { q: "What is 'Labeling' in data preparation?", a: ["Using a pen", "Assigning tags (e.g., 'Normal' or 'Malicious') to data for supervised learning", "A type of file", "A network tool"], correct: 1 },
        { q: "What is 'Synthetic' data?", a: ["Fake data", "Artificially generated data that mimics real-world data properties", "A type of cloth", "A network speed"], correct: 1 },
        { q: "What is 'Data Cleaning'?", a: ["Using soap", "Removing errors, duplicates, and irrelevant info from a dataset", "A type of wash", "A server update"], correct: 1 },
        { q: "What is 'Overfitting'?", a: ["Clothes being too tight", "When a model learns training data too well and fails on new data", "A type of exercise", "A network speed"], correct: 1 },
        { q: "What is 'Underfitting'?", a: ["Clothes being too loose", "When a model is too simple to learn the underlying patterns in data", "A type of growth", "A server reboot"], correct: 1 },
        { q: "What is 'Imbalanced' data?", a: ["Leaning to one side", "When one class (e.g., 'Normal') far outnumbers another (e.g., 'Attack')", "A type of scale", "A network speed"], correct: 1 },
        { q: "What is 'Augmentation' of data?", a: ["Deleting data", "Techniques used to increase the size/diversity of a dataset", "A type of surgery", "A server update"], correct: 1 },
        { q: "What is 'Data Drift'?", a: ["Moving a car", "When the statistical properties of the target variable change over time", "A type of wave", "A network speed"], correct: 1 },
        { q: "What is 'Differential Privacy' in datasets?", a: ["Keeping secrets", "Techniques to share information about a dataset without exposing individuals", "A type of lock", "A network protocol"], correct: 1 },
        { q: "What is 'Anonymization'?", a: ["Being famous", "Removing PII from a dataset to protect user privacy", "A type of name", "A server reboot"], correct: 1 },
        { q: "What is 'Normalization'?", a: ["Being normal", "Scaling numerical data to a standard range (e.g., 0 to 1)", "A type of math", "A network tool"], correct: 1 },
        { q: "What is 'Feature Engineering'?", a: ["Building a bridge", "The process of selecting and transforming raw data into useful features", "A type of design", "A server update"], correct: 1 },
        { q: "What is 'GDPR' impact on AI data?", a: ["A type of law", "Laws that restrict how personal data can be collected and used for AI", "A type of speed", "A network site"], correct: 1 },
        { q: "What is 'Sampling'?", a: ["Tasting food", "Selecting a subset of data from a large population to represent it", "A type of test", "A network level"], correct: 1 },
        { q: "What is 'Scrubbing' sensitive data?", a: ["Cleaning a floor", "Detecting and removing sensitive info like credit card numbers from logs", "A type of wash", "A server hub"], correct: 1 },
        { q: "What is 'Data Provenance'?", a: ["Where data came from", "Tracking the origin and history of data in a dataset", "A type of map", "A network speed"], correct: 1 },
        { q: "What is 'Label Leakage'?", a: ["A leaky bucket", "When info that wouldn't be available at prediction time is in the training data", "A type of bug", "A server update"], correct: 1 },
        { q: "Why is 'Diversity' in a dataset important?", a: ["To be nice", "To ensure the AI model works well for all types of users and scenarios", "A type of walk", "A network speed"], correct: 1 }
    ],

    // === INTERMEDIATE: AI SECURITY ===
    'ai_anomaly': [
        { q: "What is 'Anomaly Detection' in AI?", a: ["Finding friends", "Identifying data points that don't fit the normal pattern", "A type of speed", "A server reboot"], correct: 1 },
        { q: "Which algorithm is commonly used for unsupervised anomaly detection?", a: ["Isolation Forest", "Linear Regression", "Fizz Buzz", "Bubble Sort"], correct: 0 },
        { q: "What is a 'Baseline' in anomaly detection?", a: ["A starting line", "The profile of normal system behavior used for comparison", "A type of database", "A network speed"], correct: 1 },
        { q: "What is 'Multivariate' anomaly detection?", a: ["Many colors", "Analyzing multiple variables simultaneously to find complex threats", "A type of math", "A server update"], correct: 1 },
        { q: "What is a 'False Alarm'?", a: ["A real fire", "An incorrectly identified anomaly (False Positive)", "A type of bell", "A network error"], correct: 1 },
        { q: "How does AI handle 'Zero-Day' anomalies?", a: ["By ignoring them", "By detecting behavior that has never been seen before in the baseline", "By checking a list", "By deleting files"], correct: 1 },
        { q: "What is 'Thresholding'?", a: ["A doorway", "Setting the sensitivity level for what counts as an anomaly", "A type of speed", "A server reboot"], correct: 1 },
        { q: "In networking, what might an AI anomaly look like?", a: ["A normal login", "A massive, unexpected burst of encrypted traffic at 3 AM", "A slow mouse", "A browser update"], correct: 1 },
        { q: "What is 'Behavioral' profiling?", a: ["Ugly clothes", "Creating a specific model of how a user or device typically acts", "A type of photo", "A network site"], correct: 1 },
        { q: "What is 'Time-Series' anomaly detection?", a: ["A movie", "Finding anomalies in data that changes over time", "A fast clock", "A server update"], correct: 1 },
        { q: "What is 'Autoencoder' in anomaly detection?", a: ["A fast car", "A neural network that learns to compress and reconstruct normal data", "A type of file", "A network tool"], correct: 1 },
        { q: "What is the 'Reconstruction Error'?", a: ["A building fail", "The difference between input and output in an autoencoder; high error = anomaly", "A type of math", "A server reboot"], correct: 1 },
        { q: "What is 'Contextual' anomaly?", a: ["A long story", "An event that is only an anomaly in a specific situation (e.g., login from a new city)", "A type of name", "A network speed"], correct: 1 },
        { q: "What is 'Point' anomaly?", a: ["A sharp pencil", "A single data point that is far from everything else", "A type of dot", "A server update"], correct: 1 },
        { q: "What is 'Collective' anomaly?", a: ["A group project", "A set of data points that are anomalous only when seen together", "A type of set", "A network protocol"], correct: 1 },
        { q: "Why is 'Explainability' hard in anomaly detection?", a: ["Too many books", "Because deep models don't always show *why* they flagged something", "A type of code", "A server reboot"], correct: 1 },
        { q: "What is 'Active Learning' in anomalies?", a: ["Running while learning", "Allowing a human to confirm if a flagged anomaly was a real threat", "A type of gym", "A network speed"], correct: 1 },
        { q: "What is 'In-line' vs 'Out-of-band' detection?", a: ["A sports game", "Detection happening in the traffic flow vs analyzing a copy of the traffic", "A type of cable", "A server update"], correct: 1 },
        { q: "What is 'Concept Drift'?", a: ["A moving car", "When the 'normal' behavior changes over time, requiring model updates", "A type of wave", "A network speed"], correct: 1 },
        { q: "The goal of AI anomaly detection is to find:", a: ["The biggest file", "The 'needle in the haystack' (the hidden threat)", "The fastest server", "The most users"], correct: 1 }
    ],

    'ai_malware': [
        { q: "How does AI classify malware?", a: ["By the file name", "By analyzing binary patterns and behavioral characteristics", "By the file size", "By the icon color"], correct: 1 },
        { q: "What is 'Static' analysis with AI?", a: ["A radio sound", "Analyzing the code without executing the program", "A type of shock", "A network speed"], correct: 1 },
        { q: "What is 'Dynamic' analysis with AI?", a: ["A powerful explosion", "Analyzing the behavior of malware as it runs in a sandbox", "A type of motion", "A server update"], correct: 1 },
        { q: "What is a 'Malware Family'?", a: ["Malware with parents", "A group of malware programs with similar origins and code", "A type of virus", "A network hub"], correct: 1 },
        { q: "What is 'Obfuscation'?", a: ["Being famous", "Techniques used by malware to hide its code from analysis", "A type of design", "A network protocol"], correct: 1 },
        { q: "How does AI detect 'Polymorphic' malware?", a: ["By its name", "By identifying underlying behavioral patterns despite code changes", "By its size", "A server reboot"], correct: 1 },
        { q: "What is 'Packing' in malware?", a: ["Using a suitcase", "Compressing or encrypting malware to hide its true purpose", "A type of storage", "A network speed"], correct: 1 },
        { q: "What is a 'Control Flow Graph' (CFG)?", a: ["A type of map", "A representation of all paths code can take; used by AI for matching", "A type of chart", "A server update"], correct: 1 },
        { q: "What is 'Entropy' analysis?", a: ["A type of energy", "Measuring the randomness in a file; high entropy can mean encryption/packing", "A type of math", "A network speed"], correct: 1 },
        { q: "What is 'Sandbox Evasion'?", a: ["Escaping a park", "Malware detecting it's in a VM and refusing to run malicious code", "A type of exit", "A server reboot"], correct: 1 },
        { q: "What is 'Transfer Learning' in malware detection?", a: ["School bus", "Applying knowledge from one task (e.g., image recognition) to another", "A type of travel", "A network tool"], correct: 1 },
        { q: "What is 'Adversarial Patching'?", a: ["A medical patch", "Adding specific bytes to a file to fool an AI into thinking it's safe", "A type of fix", "A server update"], correct: 1 },
        { q: "What is 'Heuristic' scoring?", a: ["A type of game", "Assigning scores based on suspicious features to determine risk", "A type of search", "A network protocol"], correct: 1 },
        { q: "What is 'Metadata' in malware analysis?", a: ["The main code", "Header info, strings, and import tables used for AI classification", "A type of file", "A server reboot"], correct: 1 },
        { q: "What is 'API Hooking'?", a: ["Going fishing", "Intercepting calls between an app and the OS to observe behavior", "A type of design", "A network tool"], correct: 1 },
        { q: "What is 'Machine Learning' classifiers for malware?", a: ["A type of bin", "Algorithms like Random Forest used to categorize files as safe or malicious", "A type of drive", "A server update"], correct: 1 },
        { q: "What is 'Behavioral DNA'?", a: ["Biological code", "A unique signature of how a malware family acts on a system", "A type of search", "A network speed"], correct: 1 },
        { q: "What is 'Cloud-based' AI analysis?", a: ["Rainy weather", "Uploading suspicious files to a powerful central AI for testing", "A type of storage", "A server reboot"], correct: 1 },
        { q: "What is 'False Negative' risk in malware?", a: ["A good thing", "A dangerous file bypasses detection and infects the system", "A type of bug", "A server update"], correct: 1 },
        { q: "What is the future of malware analysis?", a: ["Manual checking", "Fully automated, AI-driven detection and mitigation", "A slow computer", "A network law"], correct: 1 }
    ],

    'ai_ids': [
        { q: "What is an 'IDS'?", a: ["Internal Data System", "Intrusion Detection System", "Internet Device Standard", "Identity Digital Service"], correct: 1 },
        { q: "What is 'NIDS'?", a: ["New IDS", "Network-based IDS (monitors all traffic)", "Node IDS", "Normal IDS"], correct: 1 },
        { q: "What is 'HIDS'?", a: ["Hidden IDS", "Host-based IDS (monitors a single device)", "Hardened IDS", "Highspeed IDS"], correct: 1 },
        { q: "What is the difference between IDS and IPS?", a: ["None", "IDS detects; IPS (Intrusion Prevention System) detects and blocks", "IDS is faster", "IPS is for macs"], correct: 1 },
        { q: "How does AI improve legacy IDS?", a: ["By making it look better", "By detecting unknown 'Zero-Day' attacks instead of just signatures", "By deleting logs", "By browsing the web"], correct: 1 },
        { q: "What is 'Packet Inspection'?", a: ["Checking a box", "Analyzing the contents of network packets for threats", "A type of speed", "A server reboot"], correct: 1 },
        { q: "What is 'Flow-based' detection?", a: ["Water moving", "Analyzing the metadata of a connection (IPs, Ports, Duration) instead of payload", "A type of wave", "A network tool"], correct: 1 },
        { q: "What is 'Stateful' inspection?", a: ["A big country", "Keeping track of the state of network connections to detect anomalies", "A type of design", "A server update"], correct: 1 },
        { q: "What is 'Alert Fatigue'?", a: ["Being tired of coffee", "Security teams becoming overwhelmed by thousands of false alerts", "A type of bug", "A network speed"], correct: 1 },
        { q: "How does AI reduce alert fatigue?", a: ["By turning off alerts", "By automatically filtering and prioritizing the most important incidents", "By deleting files", "A server reboot"], correct: 1 },
        { q: "What is 'DPI'?", a: ["Dots Per Inch", "Deep Packet Inspection", "Digital Process Interface", "Direct Path IP"], correct: 1 },
        { q: "What is 'Encrypted Traffic Analysis' (ETA) with AI?", a: ["Reading a secret", "Detecting threats in encrypted traffic without decrypting the data", "A type of code", "A network protocol"], correct: 1 },
        { q: "What is 'Botnet' detection in IDS?", a: ["Finding robots", "Identifying patterns of communication to a command-and-control server", "A type of search", "A server update"], correct: 1 },
        { q: "What is 'Lateral Movement' detection?", a: ["Walking sideways", "Identifying an attacker moving between internal systems", "A type of speed", "A network tool"], correct: 1 },
        { q: "What is 'Data Exfiltration'?", a: ["A data entry", "Unauthorized transfer of sensitive data outside the network", "A type of storage", "A server reboot"], correct: 1 },
        { q: "What is 'Honeypot' integration with IDS?", a: ["A trap", "Using fake targets to identify and block scanners before they find real ones", "A type of jar", "A network speed"], correct: 1 },
        { q: "What is 'Security Orchestration, Automation, and Response' (SOAR)?", a: ["Flying high", "Tools that help automate the response to IDS alerts", "A type of plane", "A server update"], correct: 1 },
        { q: "What is 'Baseline' drift?", a: ["A moving car", "When normal network behavior changes, causing false IDS alerts", "A type of wave", "A network tool"], correct: 1 },
        { q: "What is 'Signature-based' detection?", a: ["A pen", "Matching traffic against a database of known attack patterns", "A type of name", "A server reboot"], correct: 1 },
        { q: "What is the main limitation of signature-based IDS?", a: ["Too expensive", "It cannot detect new, unknown attacks", "Too slow", "Too small"], correct: 1 }
    ],

    // === PROFESSIONAL: AI SECURITY ===
    'ai_adversarial': [
        { q: "What is an 'Adversarial Attack' on AI?", a: ["A friendly game", "Intentionally designed inputs that trick an AI model into making a mistake", "A server update", "A type of virus"], correct: 1 },
        { q: "What is an 'Evasion Attack'?", a: ["Hiding in a box", "Providing malicious input during inference to fool the model", "A type of speed", "A network protocol"], correct: 1 },
        { q: "What is 'Data Poisoning'?", a: ["Adding poison", "Manipulating the training data to create a 'backdoor' in the AI model", "A type of bug", "A server reboot"], correct: 1 },
        { q: "What is 'Model Inversion'?", a: ["Turning it over", "An attack to extract sensitive training data from a model's outputs", "A type of math", "A server update"], correct: 1 },
        { q: "What is 'Model Stealing' (Extraction)?", a: ["Theft", "Querrying a target model to build a clone that mimics its behavior", "A type of link", "A network speed"], correct: 1 },
        { q: "What is an 'Adversarial Example'?", a: ["A good tip", "An input (like an image) slightly modified to be misclassified by AI", "A type of test", "A server update"], correct: 1 },
        { q: "What is 'Black-Box' attack?", a: ["A dark box", "An attack where the attacker has no knowledge of the target model's architecture", "A type of name", "A network tool"], correct: 1 },
        { q: "What is 'White-Box' attack?", a: ["A clear box", "An attack where the attacker has full access to the model's parameters", "A type of file", "A server reboot"], correct: 1 },
        { q: "What is 'Perturbation' in AI attacks?", a: ["Being annoyed", "The small, often invisible change made to an input to fool an AI", "A type of shift", "A network speed"], correct: 1 },
        { q: "What is 'Adversarial Training'?", a: ["Fighting while training", "Training a model on both clean and adversarial examples to make it robust", "A type of gym", "A server update"], correct: 1 },
        { q: "What is 'Gradient-based' attack?", a: ["A colorful attack", "Using the model's gradients to find the direction of the most effective change", "A type of math", "A server reboot"], correct: 1 },
        { q: "What is 'Fast Gradient Sign Method' (FGSM)?", a: ["A fast car", "A popular technique for generating adversarial examples quickly", "A type of sign", "A network speed"], correct: 1 },
        { q: "What is 'Robustness' in AI?", a: ["Being strong", "A model's ability to maintain performance despite adversarial attacks", "A type of health", "A server update"], correct: 1 },
        { q: "What is a 'TrojAI' or Backdoor attack?", a: ["A horse", "A model that works normally except when triggered by a specific secret input", "A type of virus", "A network tool"], correct: 1 },
        { q: "What is 'Input Transformed' defense?", a: ["Moving a box", "Preprocessing inputs (e.g., resizing) to remove adversarial patterns", "A type of shift", "A server update"], correct: 1 },
        { q: "What is 'Defensive Distillation'?", a: ["Making water", "A technique to make it harder for attackers to find gradients for exploits", "A type of science", "A network speed"], correct: 1 },
        { q: "What is 'Targeted' attack vs 'Non-targeted'?", a: ["Specific vs Random", "Forcing a specific wrong answer vs just any wrong answer", "A type of goal", "A server update"], correct: 1 },
        { q: "What is 'Universal' adversarial perturbation?", a: ["Space travel", "A single pattern that can fool an AI on many different inputs", "A type of map", "A network protocol"], correct: 1 },
        { q: "What is 'Physical World' adversarial attack?", a: ["A real punch", "An attack that works through a camera (e.g., a sticker on a stop sign)", "A type of wall", "A network speed"], correct: 1 },
        { q: "Why is Adversarial AI dangerous?", a: ["Too expensive", "It can compromise the safety of autonomous vehicles and medical AI", "Too slow", "A network law"], correct: 1 }
    ],

    'ai_behavioral': [
        { q: "What is 'User Behavior Analytics' (UBA)?", a: ["Watching people", "Using AI to model and detect deviations in human activity", "A type of report", "A network speed"], correct: 1 },
        { q: "What is 'Entity Analytics'?", a: ["Finding ghosts", "Analyzing behavior of non-human actors like servers and IoT devices", "A type of search", "A server update"], correct: 1 },
        { q: "What is an 'Insider Threat' + AI?", a: ["A spy", "Detecting an employee stealing data based on subtle behavior changes", "A type of virus", "A network tool"], correct: 1 },
        { q: "What is 'Privileged Account' monitoring?", a: ["A high-level view", "Using AI to watch for abuse of admin or root credentials", "A type of lock", "A server reboot"], correct: 1 },
        { q: "What is 'Session' analysis?", a: ["A long meeting", "Analyzing the entire duration of a user login for suspicious activity", "A type of timer", "A network speed"], correct: 1 },
        { q: "What is 'Risk Scoring'?", a: ["A game score", "Assigning a numerical threat level to every user and event based on behavior", "A type of math", "A server update"], correct: 1 },
        { q: "What is 'Adaptive' Authentication?", a: ["A smart tool", "Requesting MFA only when a user's behavior seems high-risk", "A type of login", "A network speed"], correct: 1 },
        { q: "What is 'Data Access' patterns?", a: ["Looking at files", "AI observing which files a user normally touches to detect theft", "A type of map", "A server update"], correct: 1 },
        { q: "What is 'Time-of-day' anomaly?", a: ["Sleeping", "A user logging in at 4 AM when they usually work at 9 AM", "A type of clock", "A network site"], correct: 1 },
        { q: "What is 'Geographic' anomaly?", a: ["Traveling", "A user logging in from Sweden one hour after logging in from Ohio", "A type of map", "A server update"], correct: 1 },
        { q: "What is 'Unusual Command' sequence?", a: ["Typing fast", "Detecting a developer running hacker tools they never used before", "A type of search", "A network speed"], correct: 1 },
        { q: "What is 'Endpoint' behavior?", a: ["The end of a line", "Analyzing how a program interacts with files and the network", "A type of screen", "A server update"], correct: 1 },
        { q: "What is 'Peers Group' comparison?", a: ["Looking at friends", "Comparing a user's behavior to others in the same role to find outliers", "A type of test", "A network speed"], correct: 1 },
        { q: "What is 'Alert Fatigue' in UBA?", a: ["Being tired", "Dealing with too many false alarms about normal user behavior", "A type of bug", "A server update"], correct: 1 },
        { q: "How does AI handle 'Legitimate' changes?", a: ["By blocking them", "By learning that a user's role has changed and updating their baseline", "By deleting files", "A server reboot"], correct: 1 },
        { q: "What is 'Account Takeover' (ATO) detection?", a: ["A car theft", "Detecting when a hacker is using a stolen legitimate account", "A type of lock", "A network tool"], correct: 1 },
        { q: "What is 'Continuous' monitoring?", a: ["Never sleeping", "AI constantly analyzing behavior, not just at login", "A type of clock", "A server update"], correct: 1 },
        { q: "What is 'Privileged Identity Management' (PIM)?", a: ["Finding a name", "Tools and AI that manage access to sensitive accounts", "A type of list", "A network speed"], correct: 1 },
        { q: "What is 'DLP' (Data Loss Prevention) + AI?", a: ["Saving data", "AI identifies sensitive content in files before they leave the network", "A type of shield", "A server update"], correct: 1 },
        { q: "What is the goal of Behavioral Analysis?", a: ["To be a spy", "To find threats that have already bypassed the perimeter", "To be fast", "To be cheap"], correct: 1 }
    ],

    'ai_automation': [
        { q: "What is 'Autonomous Defense'?", a: ["A smart shield", "Security systems that detect and respond to attacks without human help", "A type of robot", "A network speed"], correct: 1 },
        { q: "What is 'SOAR'?", a: ["Flying high", "Security Orchestration, Automation, and Response", "System Online Alpha Route", "Simple Office Auto Record"], correct: 1 },
        { q: "What is an 'Automated Response'?", a: ["An instant reply", "An action taken by a machine to mitigate a threat (e.g., blocking an IP)", "A type of bot", "A server update"], correct: 1 },
        { q: "What is 'Orchestration' in security?", a: ["A concert", "Connecting different security tools so they work together automatically", "A type of design", "A network speed"], correct: 1 },
        { q: "What is a 'Playbook' in SOAR?", a: ["A book for sports", "A pre-defined set of automated steps to handle a specific threat", "A type of manual", "A server update"], correct: 1 },
        { q: "What is 'Self-Healing' systems?", a: ["Medicine", "Systems that automatically repair themselves after an attack", "A type of health", "A network tool"], correct: 1 },
        { q: "What is 'Automated Patching'?", a: ["Fixing clothes", "AI automatically applying security updates across a network", "A type of stitch", "A server reboot"], correct: 1 },
        { q: "What is 'Threat Hunting' automation?", a: ["Going to the woods", "AI proactively searching for hidden threats in a network", "A type of hunt", "A network speed"], correct: 1 },
        { q: "What is 'Dynamic' policy enforcement?", a: ["A fast move", "Automatically changing firewall rules based on real-time threat levels", "A type of law", "A server update"], correct: 1 },
        { q: "What is 'AI-to-AI' security?", a: ["A conversation", "AI defense systems fighting against AI-driven attacks", "A type of game", "A network level"], correct: 1 },
        { q: "What is 'Incident Reconstruction'?", a: ["Building a house", "AI automatically piecing together how an attack happened", "A type of art", "A server reboot"], correct: 1 },
        { q: "What is 'Automated Deception'?", a: ["Lying", "AI automatically creating and moving fake targets (honeypots)", "A type of trick", "A network tool"], correct: 1 },
        { q: "What is 'Zero-Touch' provisioning?", a: ["Not touching", "Setting up new devices with full security automatically", "A type of reach", "A server update"], correct: 1 },
        { q: "What is the benefit of Automation?", a: ["It's fun", "Faster response times and reducing human error", "It's cheap", "It's cool"], correct: 1 },
        { q: "What is the 'Human-in-the-loop'?", a: ["A circle of people", "A model where AI handles the work but a human makes the final choice", "A type of game", "A server site"], correct: 1 },
        { q: "What is 'Scale' in automation?", a: ["A weight", "The ability to handle thousands of incidents simultaneously", "A type of climb", "A network speed"], correct: 1 },
        { q: "What is 'MTTR'?", a: ["My Total Time Record", "Mean Time To Respond (or Repair)", "Master Task Tech Route", "Main Tech Time Reset"], correct: 1 },
        { q: "What is 'False Positive' in automation?", a: ["A good thing", "When a computer automatically blocks a legitimate user", "A type of bug", "A server update"], correct: 1 },
        { q: "What is 'Edge' AI automation?", a: ["Being cool", "Running automation directly on the local device, not in the cloud", "A type of border", "A network level"], correct: 1 },
        { q: "What is the ultimate goal of AI automation?", a: ["To fire everyone", "To create a resilient, self-defending digital infrastructure", "To be fast", "To be lazy"], correct: 1 }
    ]
};
